---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true

requirements:
    requiredStorage:    8
    requiredRam:        1.0
    internetCheckUrl:	https://ubuntu.com

    check:
        - storage
        - ram
        - power
        - root
    required:
        - root
        - storage
        - ram

geoip:
    style:  "none"
